# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 02:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import pipeline.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_auto_20160915_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_poster_frames_id',
            field=models.CharField(default=pipeline.utils.generate_long_random_id, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
